apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-app
  template:
    metadata:
      labels:
        app: ollama-app
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          command: ["ollama", "serve"]
      initContainers:
        - name: ollama-init
          image: ollama/ollama:latest
          command: ["ollama", "pull", "llama3"]
