image:
  repository: beyzanurcelik/aikoduretici
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30007

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ollama:
  tag: "0.6.8"
  resources:
    requests:
      memory: "6Gi"
    limits:
      memory: "8Gi"
  env:
    - name: OLLAMA_MODELS
      value: /models